apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: vq-vae-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.1, pipelines.kubeflow.org/pipeline_compilation_time: '2020-10-21T22:19:18.135794',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline to train vq-vae",
      "inputs": [{"default": "gaze", "name": "data_type", "optional": true}, {"default":
      "vq_vae", "name": "f_name", "optional": true}, {"default": "128", "name": "num_hiddens",
      "optional": true}, {"default": "32", "name": "num_residual_hiddens", "optional":
      true}, {"default": "2", "name": "num_residual_layers", "optional": true}, {"default":
      "8", "name": "embedding_dim", "optional": true}, {"default": "128", "name":
      "num_embeddings", "optional": true}, {"default": "0.25", "name": "commitment_cost",
      "optional": true}, {"default": "0.99", "name": "decay", "optional": true}, {"default":
      "500", "name": "epoch", "optional": true}, {"default": "0.001", "name": "lr",
      "optional": true}, {"default": "32", "name": "batch_size", "optional": true},
      {"default": "http://OHMORI:house101@zaku.sys.es.osaka-u.ac.jp:10080/OHMORI/vq-vae_1d.git",
      "name": "repo_url", "optional": true}], "name": "vq-vae pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.1}
spec:
  entrypoint: vq-vae-pipeline
  templates:
  - name: create-pipeline-volume
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: '{{workflow.name}}-pipeline-pvc'
        spec:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
    outputs:
      parameters:
      - name: create-pipeline-volume-manifest
        valueFrom: {jsonPath: '{}'}
      - name: create-pipeline-volume-name
        valueFrom: {jsonPath: '{.metadata.name}'}
      - name: create-pipeline-volume-size
        valueFrom: {jsonPath: '{.status.capacity.storage}'}
  - name: git-clone
    container:
      args: [-c, 'git clone {{inputs.parameters.repo_url}} /workspace/vq-vae_1d &&
          pwd && ls']
      command: [sh]
      image: alpine/git:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - {mountPath: /workspace, name: create-pipeline-volume}
    inputs:
      parameters:
      - {name: create-pipeline-volume-name}
      - {name: repo_url}
    volumes:
    - name: create-pipeline-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.create-pipeline-volume-name}}'}
  - name: vq-vae
    container:
      args: [--data_type, '{{inputs.parameters.data_type}}', --f_name, '{{inputs.parameters.f_name}}',
        --num_hiddens, '{{inputs.parameters.num_hiddens}}', --num_residual_hiddens,
        '{{inputs.parameters.num_residual_hiddens}}', --num_residual_layers, '{{inputs.parameters.num_residual_layers}}',
        --embedding_dim, '{{inputs.parameters.embedding_dim}}', --num_embeddings,
        '{{inputs.parameters.num_embeddings}}', --commitment_cost, '{{inputs.parameters.commitment_cost}}',
        --decay, '{{inputs.parameters.decay}}', --epoch, '{{inputs.parameters.epoch}}',
        --lr, '{{inputs.parameters.lr}}', --batch_size, '{{inputs.parameters.batch_size}}']
      command: [python3, train.py]
      image: zaku.sys.es.osaka-u.ac.jp:10081/ohmori/vq-vae_1d:v0.0.0
      resources:
        limits: {nvidia.com/gpu: 1}
      volumeMounts:
      - {mountPath: /home/jovyan, name: create-pipeline-volume}
      - {mountPath: /workspace, name: create-pipeline-volume}
      - {mountPath: /home/jovyan/vq-vae_1d/data, name: data}
      - {mountPath: /home/jovyan/vq-vae_1d/script/pth, name: pth}
      - {mountPath: /home/jovyan/vq-vae_1d/script/logs, name: logs}
      workingDir: /home/jovyan/vq-vae_1d/script
    inputs:
      parameters:
      - {name: batch_size}
      - {name: commitment_cost}
      - {name: create-pipeline-volume-name}
      - {name: data_type}
      - {name: decay}
      - {name: embedding_dim}
      - {name: epoch}
      - {name: f_name}
      - {name: lr}
      - {name: num_embeddings}
      - {name: num_hiddens}
      - {name: num_residual_hiddens}
      - {name: num_residual_layers}
    outputs:
      artifacts:
      - {name: mlpipeline-ui-metadata, path: /mlpipeline-ui-metadata.json}
    volumes:
    - name: create-pipeline-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.create-pipeline-volume-name}}'}
    - name: create-pipeline-volume
      persistentVolumeClaim: {claimName: '{{inputs.parameters.create-pipeline-volume-name}}'}
    - name: data
      nfs: {path: /data/share/data, server: 192.168.11.107}
    - name: logs
      nfs: {path: /data/share/logs, server: 192.168.11.107}
    - name: pth
      nfs: {path: /data/share/pth, server: 192.168.11.107}
  - name: vq-vae-pipeline
    inputs:
      parameters:
      - {name: batch_size}
      - {name: commitment_cost}
      - {name: data_type}
      - {name: decay}
      - {name: embedding_dim}
      - {name: epoch}
      - {name: f_name}
      - {name: lr}
      - {name: num_embeddings}
      - {name: num_hiddens}
      - {name: num_residual_hiddens}
      - {name: num_residual_layers}
      - {name: repo_url}
    dag:
      tasks:
      - {name: create-pipeline-volume, template: create-pipeline-volume}
      - name: git-clone
        template: git-clone
        dependencies: [create-pipeline-volume]
        arguments:
          parameters:
          - {name: create-pipeline-volume-name, value: '{{tasks.create-pipeline-volume.outputs.parameters.create-pipeline-volume-name}}'}
          - {name: repo_url, value: '{{inputs.parameters.repo_url}}'}
      - name: vq-vae
        template: vq-vae
        dependencies: [create-pipeline-volume, git-clone]
        arguments:
          parameters:
          - {name: batch_size, value: '{{inputs.parameters.batch_size}}'}
          - {name: commitment_cost, value: '{{inputs.parameters.commitment_cost}}'}
          - {name: create-pipeline-volume-name, value: '{{tasks.create-pipeline-volume.outputs.parameters.create-pipeline-volume-name}}'}
          - {name: data_type, value: '{{inputs.parameters.data_type}}'}
          - {name: decay, value: '{{inputs.parameters.decay}}'}
          - {name: embedding_dim, value: '{{inputs.parameters.embedding_dim}}'}
          - {name: epoch, value: '{{inputs.parameters.epoch}}'}
          - {name: f_name, value: '{{inputs.parameters.f_name}}'}
          - {name: lr, value: '{{inputs.parameters.lr}}'}
          - {name: num_embeddings, value: '{{inputs.parameters.num_embeddings}}'}
          - {name: num_hiddens, value: '{{inputs.parameters.num_hiddens}}'}
          - {name: num_residual_hiddens, value: '{{inputs.parameters.num_residual_hiddens}}'}
          - {name: num_residual_layers, value: '{{inputs.parameters.num_residual_layers}}'}
  arguments:
    parameters:
    - {name: data_type, value: gaze}
    - {name: f_name, value: vq_vae}
    - {name: num_hiddens, value: '128'}
    - {name: num_residual_hiddens, value: '32'}
    - {name: num_residual_layers, value: '2'}
    - {name: embedding_dim, value: '8'}
    - {name: num_embeddings, value: '128'}
    - {name: commitment_cost, value: '0.25'}
    - {name: decay, value: '0.99'}
    - {name: epoch, value: '500'}
    - {name: lr, value: '0.001'}
    - {name: batch_size, value: '32'}
    - {name: repo_url, value: 'http://OHMORI:house101@zaku.sys.es.osaka-u.ac.jp:10080/OHMORI/vq-vae_1d.git'}
  serviceAccountName: pipeline-runner
